# Copyright (c) 2026 Diego Silva Morais <lukewaresoftwarehouse@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# ─────────────────────────────────────────────────────────────────────────────
# context-mode plugin installer for OpenClaw
#
# Prefer: openclaw plugins install -l <src> — records install provenance and
# updates openclaw.json (see references/upstream/tools/plugin.md in OpenClaw skill).
# Fallback: copy stub + jq merge (custom volumes / CLI edge cases).
# Also syncs runtime/openclaw.runtime.json when present.
# Idempotent: safe on every container start (OPENCLAW_NO_PROMPT=1 in 00-env.sh).
# ─────────────────────────────────────────────────────────────────────────────

CONTEXT_MODE_SRC="/opt/context-mode"
EXT_DIR="${OPENCLAW_STATE_DIR}/extensions/context-mode"
OPENCLAW_JSON="${OPENCLAW_STATE_DIR}/openclaw.json"
RUNTIME_JSON="${OPENCLAW_STATE_DIR}/runtime/openclaw.runtime.json"

echo "[bootstrap] context-mode plugin setup"

# ── 1. Ensure source is available ────────────────────────────────────────────
if [ ! -d "${CONTEXT_MODE_SRC}" ]; then
  echo "[bootstrap] context-mode source not found at ${CONTEXT_MODE_SRC}; cloning..."
  git clone --depth 1 https://github.com/mksglu/context-mode.git "${CONTEXT_MODE_SRC}" \
    || { echo "[bootstrap] ERROR: failed to clone context-mode" >&2; exit 1; }
fi

# ── 2. Ensure it is built ───────────────────────────────────────────────────
if [ ! -f "${CONTEXT_MODE_SRC}/build/openclaw-plugin.js" ]; then
  echo "[bootstrap] context-mode not built; building..."
  (
    cd "${CONTEXT_MODE_SRC}"
    npm install --silent
    npm run build
    npm rebuild better-sqlite3
  ) || { echo "[bootstrap] ERROR: failed to build context-mode" >&2; exit 1; }
  echo "[bootstrap] context-mode build complete"
else
  echo "[bootstrap] context-mode already built"
fi

# ── 3. Install / link extension (CLI first — provenance + plugins.installs) ───
echo "[bootstrap] context-mode: trying openclaw plugins install -l ${CONTEXT_MODE_SRC}"
if openclaw plugins install -l "${CONTEXT_MODE_SRC}"; then
  echo "[bootstrap] context-mode linked via OpenClaw CLI"
else
  _install_ec=$?
  if [ -f "${EXT_DIR}/openclaw.plugin.json" ] || [ -L "${EXT_DIR}" ]; then
    echo "[bootstrap] context-mode: CLI exited ${_install_ec} but extension dir exists; continuing"
  else
    echo "[bootstrap] context-mode: CLI install failed (${_install_ec}); manual extension copy"
    mkdir -p "${EXT_DIR}"
    cp "${CONTEXT_MODE_SRC}/openclaw.plugin.json" "${EXT_DIR}/openclaw.plugin.json"
    cat > "${EXT_DIR}/index.ts" << TSEOF
// context-mode OpenClaw global extension — auto-generated by bootstrap fallback.
export { default } from "${CONTEXT_MODE_SRC}/build/openclaw-plugin.js";
TSEOF
    echo "[bootstrap] extension files copied (fallback)"
  fi
fi

if [ -f "${OPENCLAW_JSON}" ]; then
  mkdir -p ~/.openclaw
  cp -f "${OPENCLAW_JSON}" ~/.openclaw/openclaw.json || true
fi

# ── 4. Clear jiti cache (stale compiled TS) ─────────────────────────────────
rm -f /tmp/jiti/context-mode-index.*.cjs /tmp/jiti/build-openclaw-plugin.*.cjs 2>/dev/null || true

# ── 4b. Pin trust + load-path provenance in openclaw.json (idempotent) ───────
# OpenClaw warns if a plugin is only present under extensions/ without
# plugins.allow and plugins.load.paths (see openclaw/openclaw#43655).
if [ -f "${OPENCLAW_JSON}" ]; then
  echo "[bootstrap] merging context-mode into openclaw.json (allow + load.paths + entries)"
  _oc_tmp="$(mktemp)"
  if jq --arg p "${EXT_DIR}" '
    .plugins = (.plugins // {})
    | .plugins.allow = ((.plugins.allow // []) + ["context-mode"] | unique)
    | .plugins.load = (.plugins.load // {})
    | .plugins.load.paths = ((.plugins.load.paths // []) + [$p] | unique)
    | .plugins.entries = (.plugins.entries // {})
    | .plugins.entries["context-mode"] = ((.plugins.entries["context-mode"] // {}) + {"enabled": true})
  ' "${OPENCLAW_JSON}" > "${_oc_tmp}"; then
    mv "${_oc_tmp}" "${OPENCLAW_JSON}"
    mkdir -p ~/.openclaw
    cp "${OPENCLAW_JSON}" ~/.openclaw/openclaw.json
    echo "[bootstrap] openclaw.json updated for context-mode provenance"
  else
    rm -f "${_oc_tmp}"
    echo "[bootstrap] warning: jq failed merging context-mode into openclaw.json" >&2
  fi
else
  echo "[bootstrap] warning: openclaw.json missing; cannot register context-mode load paths yet" >&2
fi

# ── 5. Register in runtime.json (idempotent) ────────────────────────────────
if [ -f "${RUNTIME_JSON}" ]; then
  echo "[bootstrap] registering context-mode in runtime.json"
  node -e "
const fs = require('fs');
const runtimePath = process.argv[1];
let cfg;
try {
  cfg = JSON.parse(fs.readFileSync(runtimePath, 'utf8'));
} catch (e) {
  console.error('  [context-mode] warning: failed to parse runtime.json — will retry after doctor');
  process.exit(0);
}
const plugins = cfg.plugins ??= {};
const allow = plugins.allow ??= [];
if (!allow.includes('context-mode')) {
  allow.unshift('context-mode');
  console.log('  [context-mode] added to plugins.allow');
} else {
  console.log('  [context-mode] already in plugins.allow');
}
const entries = plugins.entries ??= {};
if (!entries['context-mode']) {
  entries['context-mode'] = { enabled: true };
  console.log('  [context-mode] added to plugins.entries');
} else {
  console.log('  [context-mode] already in plugins.entries');
}
fs.writeFileSync(runtimePath, JSON.stringify(cfg, null, 2) + '\n');
console.log('  [context-mode] runtime.json updated');
" "${RUNTIME_JSON}"
else
  echo "[bootstrap] runtime.json not found yet; will register after doctor"
  # Create a deferred registration hook that runs after doctor generates runtime.json
  _deferred_marker="${OPENCLAW_STATE_DIR}/.context-mode-register-pending"
  touch "${_deferred_marker}"
fi

# ── 6. Deferred registration (runs if runtime.json was missing at step 5) ───
context_mode_deferred_register() {
  local _marker="${OPENCLAW_STATE_DIR}/.context-mode-register-pending"
  [ -f "${_marker}" ] || return 0

  local _retries="${CONTEXT_MODE_REGISTER_RETRIES:-30}"
  local _interval="${CONTEXT_MODE_REGISTER_INTERVAL:-2}"

  for _ in $(seq 1 "${_retries}"); do
    if [ -f "${RUNTIME_JSON}" ]; then
      echo "[bootstrap] runtime.json found; registering context-mode (deferred)"
      node -e "
const fs = require('fs');
const runtimePath = process.argv[1];
let cfg;
try {
  cfg = JSON.parse(fs.readFileSync(runtimePath, 'utf8'));
} catch (e) {
  console.error('  [context-mode] warning: failed to parse runtime.json');
  process.exit(1);
}
const plugins = cfg.plugins ??= {};
const allow = plugins.allow ??= [];
if (!allow.includes('context-mode')) allow.unshift('context-mode');
const entries = plugins.entries ??= {};
if (!entries['context-mode']) entries['context-mode'] = { enabled: true };
fs.writeFileSync(runtimePath, JSON.stringify(cfg, null, 2) + '\n');
console.log('  [context-mode] runtime.json updated (deferred)');
" "${RUNTIME_JSON}"
      rm -f "${_marker}"
      return 0
    fi
    sleep "${_interval}"
  done
  echo "[bootstrap] warning: runtime.json not found after ${_retries} retries; context-mode not registered"
  return 0
}

# Run deferred registration in background (non-blocking)
if [ -f "${OPENCLAW_STATE_DIR}/.context-mode-register-pending" ]; then
  echo "[bootstrap] starting deferred context-mode registration watcher"
  ( set +e; context_mode_deferred_register ) &
fi

# ── 7. Verify ───────────────────────────────────────────────────────────────
# CLI link: EXT_DIR may be a symlink to package root (manifest via openclaw.extensions).
if [ -f "${EXT_DIR}/openclaw.plugin.json" ]; then
  echo "[bootstrap] context-mode plugin ready (extension dir: ${EXT_DIR})"
else
  echo "[bootstrap] warning: context-mode manifest missing under ${EXT_DIR}" >&2
fi

echo "[bootstrap] context-mode plugin setup done"
